Spike/complete podman support
devfile/registry-support pull request #235
Opened 2024-04-18 17:20 UTC by Jdubrick

**Please specify the area for this PR**
Build scripts

**What does does this PR do / why we need it**:
Enables `podman` to be used as a container engine for the build scripts in `/oci-registry`.

**Which issue(s) this PR fixes**:

Fixes https://github.com/devfile/api/issues/1503

**PR acceptance criteria**:

- [ ] Test Coverage 
    - Are your changes sufficiently tested, and are any applicable test cases added or updated to cover your changes?

Documentation (WIP)
- [ ] Does the [REST API doc](../index/server/registry-REST-API.adoc) need to be updated with your changes?
- [ ] Does the [registry library doc](../registry-library/README.md) need to be updated with your changes?

**How to test changes / Special notes to the reviewer**:
1. cd `oci-registry`
2. Run `export USE_PODMAN=true`
3. Run `bash build.sh` and/or `bash push.sh <repository-tag>`

2024-04-18 20:58 UTC, michael-valdron requested changes
These suggested changes allow you to run OCI registry `build.sh` script from anywhere.

2024-04-18 20:58 UTC, michael-valdron commented on oci-registry/build.sh
>  buildfolder="$(basename "$(dirname "$0")")"
Perhaps we could reuse `buildfolder` in this case:
```suggestion
# OCI registry build directory
buildfolder="$(basename "$(dirname "$0")")"

# set podman alias if necessary
. ${buildfolder}/../setenv.sh

# Build the index container for the registry
```

2024-04-18 20:58 UTC, michael-valdron commented on oci-registry/push.sh
> +. ../setenv.sh
```suggestion
. $(basename "$(dirname "$0")")/../setenv.sh
```

2024-04-18 21:11 UTC, michael-valdron reviewed
Also gave feedback to your issue comment: https://github.com/devfile/api/issues/1503#issuecomment-2065330828

2024-04-19 15:01 UTC, Jdubrick commented
@michael-valdron new commit adopts your changes to allow `build.sh` and `push.sh` from `/oci-registry` to be run from the root of the repository `/` or from `/oci-registry`.

2024-04-19 19:35 UTC, michael-valdron approved these changes
/lgtm

Looks good!

2024-04-19 19:41 UTC, merged