Sample support for index generator
devfile/registry-support pull request #45
Opened 2021-04-23 20:10 UTC by GeekArthur

Signed-off-by: jingfu wang <jingfwan@redhat.com>

**Please specify the area for this PR**
index generator

**What does does this PR do / why we need it**:
This PR modifies the index generator to let it parse extraDevfileEntires.yaml and generate index.json with both stacks and samples

**Which issue(s) this PR fixes**:

Related issues:
https://github.com/devfile/api/issues/279
https://github.com/devfile/api/issues/403
https://github.com/devfile/api/issues/409

**PR acceptance criteria**:

- [x] Test (WIP) 

- [x] Documentation (WIP)

**How to test changes / Special notes to the reviewer**:
1. Build the index generator
2. Run the binary to generate index.json then verify it (Note: the registry path is the registry root directory)

2021-04-26 18:01 UTC, johnmcollier requested changes
Left a couple comments.

2021-04-26 19:34 UTC, GeekArthur commented on index/generator/library/library.go
> +	// Parse extraDevfileEntries.yaml
Sure, I can make the changes and add unit tests.

2021-04-27 16:47 UTC, GeekArthur commented on index/generator/library/library.go
> +	// Parse extraDevfileEntries.yaml
Done

2021-04-27 16:47 UTC, GeekArthur commented on index/generator/library/library.go
> +func validateIndexComponent(indexComponent schema.Schema, componentType string) error {
Done

2021-04-27 16:49 UTC, GeekArthur commented
@johnmcollier Thanks for reviewing, I refactored the functions and added the unit tests, please review again.

2021-04-27 18:41 UTC, johnmcollier approved these changes
Looks good, great job on the tests too 👍

2021-04-27 18:59 UTC, merged