Modify index generator validator
devfile/registry-support pull request #55
Opened 2021-05-13 15:58 UTC by GeekArthur

Signed-off-by: jingfu wang <jingfwan@redhat.com>

**Please specify the area for this PR**
Index generator

**What does does this PR do / why we need it**:
This PR modify index generator validator to restrict the number of git remotes to 1

**Which issue(s) this PR fixes**:
Issue from this comment: https://github.com/devfile/api/pull/445#discussion_r628469526

**PR acceptance criteria**:

- [x] Test (WIP) 

- [x] Documentation (WIP)

**How to test changes / Special notes to the reviewer**:

2021-05-17 15:45 UTC, johnmcollier requested changes
Can you add a test case for this change?

2021-05-17 17:03 UTC, GeekArthur commented
> Can you add a test case for this change?

Sure, will add it.

2021-05-17 18:48 UTC, GeekArthur commented
@johnmcollier I just added the test case, please review again.

2021-05-19 15:39 UTC, johnmcollier approved these changes

2021-05-19 15:46 UTC, merged