Mutiple registries query support
devfile/registry-support pull request #63
Opened 2021-06-22 18:40 UTC by GeekArthur

Signed-off-by: Jingfu Wang <jingfwan@redhat.com>

**Please specify the area for this PR**
Registry library

**What does does this PR do / why we need it**:
This PR adds the support for multiple registries query.

**Which issue(s) this PR fixes**:

Fixes https://github.com/devfile/api/issues/377

**PR acceptance criteria**:

- [ ] Test (WIP) 

- [ ] Documentation (WIP)

**How to test changes / Special notes to the reviewer**:
1. Build the registry library CLI then connect to multiple registries by running `export REGISTRY_LIST=https://registry.devfile.io/,http://devfile-registry.192.168.64.2.nip.io`
2. Run `./registry-library list --type stack` to list stacks from multiple registries

2021-06-25 15:02 UTC, johnmcollier requested changes
Left some review comments.

2021-06-25 18:39 UTC, GeekArthur commented on tests/integration/pkg/tests/devfilelibrary_tests.go
> +	devfileStageRegistry  = "https://registry.stage.devfile.io"
Sure, will update those to get them from the config.

2021-06-25 18:40 UTC, GeekArthur commented on tests/integration/cmd/devfileregistry_test.go
> +	registryList := os.Getenv("REGISTRY_LIST")
Sounds good, will update it.

2021-06-25 18:40 UTC, GeekArthur commented on registry-library/library/library.go
> +	fmt.Fprintln(w, "Name", "\t", "Description", "\t", "Registry", "\t", "Error", "\t")
It's not used by odo, only the `registry-library` uses it for testing, so no breaking changes for odo.

2021-06-25 18:48 UTC, GeekArthur commented on registry-library/library/library.go
> +func GetMultipleRegistriesIndices(registryURLs []string, devfileTypes ...indexSchema.DevfileType) []Registry {
> Can you add unit tests for this function if possible?
The integration test uses `registry-library` CLI for testing and the `registry-library` calls the function directly, given that do you think we still need the unit test for this function? IMO, the integration test already covered the unit test as there are no logic/code block between `registry-library` and the function itself.

2021-06-29 15:21 UTC, johnmcollier commented on registry-library/library/library.go
> +func GetMultipleRegistriesIndices(registryURLs []string, devfileTypes ...indexSchema.DevfileType) []Registry {
I'm fine with that

2021-06-29 15:37 UTC, GeekArthur commented
@johnmcollier Comments addressed, please review again.

2021-06-30 15:23 UTC, johnmcollier approved these changes

2021-06-30 21:36 UTC, merged